
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 16 18:41:05 CET 2009
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Mon Mar 16 18:41:05 CET 2009
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\044\000\002\003\003\000\002\002\004\000\002\003" +
    "\004\000\002\004\003\000\002\004\004\000\002\005\010" +
    "\000\002\005\010\000\002\005\007\000\002\005\005\000" +
    "\002\005\004\000\002\005\003\000\002\006\005\000\002" +
    "\006\004\000\002\007\003\000\002\007\003\000\002\010" +
    "\005\000\002\010\006\000\002\011\005\000\002\011\006" +
    "\000\002\011\005\000\002\011\006\000\002\012\003\000" +
    "\002\012\005\000\002\013\006\000\002\013\010\000\002" +
    "\014\003\000\002\014\004\000\002\015\010\000\002\016" +
    "\004\000\002\017\003\000\002\017\004\000\002\020\004" +
    "\000\002\020\004\000\002\021\006\000\002\022\010\000" +
    "\002\023\016" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\135\000\012\003\012\004\015\005\006\006\005\001" +
    "\002\000\010\003\ufff3\004\ufff3\022\ufff3\001\002\000\004" +
    "\022\125\001\002\000\004\022\116\001\002\000\004\002" +
    "\114\001\002\000\010\002\ufffe\003\012\004\015\001\002" +
    "\000\006\003\012\004\015\001\002\000\020\002\ufff7\003" +
    "\ufff7\004\ufff7\012\101\013\076\016\077\022\100\001\002" +
    "\000\010\003\ufff4\004\ufff4\022\ufff4\001\002\000\004\002" +
    "\001\001\002\000\004\022\016\001\002\000\004\012\017" +
    "\001\002\000\010\005\006\006\005\011\021\001\002\000" +
    "\004\016\075\001\002\000\004\014\062\001\002\000\006" +
    "\007\043\010\036\001\002\000\004\013\057\001\002\000" +
    "\004\022\027\001\002\000\006\007\043\010\036\001\002" +
    "\000\010\007\uffe8\010\uffe8\022\027\001\002\000\004\020" +
    "\030\001\002\000\004\022\031\001\002\000\004\021\032" +
    "\001\002\000\004\022\033\001\002\000\004\016\034\001" +
    "\002\000\010\007\uffe6\010\uffe6\022\uffe6\001\002\000\006" +
    "\007\uffe7\010\uffe7\001\002\000\004\014\052\001\002\000" +
    "\010\007\043\010\036\013\uffe4\001\002\000\004\013\ufff6" +
    "\001\002\000\004\016\050\001\002\000\004\016\047\001" +
    "\002\000\004\014\044\001\002\000\004\022\045\001\002" +
    "\000\004\015\046\001\002\000\004\016\uffe0\001\002\000" +
    "\010\007\uffe2\010\uffe2\013\uffe2\001\002\000\010\007\uffe1" +
    "\010\uffe1\013\uffe1\001\002\000\004\013\uffe3\001\002\000" +
    "\004\022\053\001\002\000\004\017\054\001\002\000\004" +
    "\022\055\001\002\000\004\015\056\001\002\000\004\016" +
    "\uffdf\001\002\000\004\016\060\001\002\000\010\002\ufffc" +
    "\003\ufffc\004\ufffc\001\002\000\004\013\ufff5\001\002\000" +
    "\004\022\063\001\002\000\004\017\064\001\002\000\004" +
    "\022\065\001\002\000\004\017\066\001\002\000\004\022" +
    "\067\001\002\000\004\017\070\001\002\000\004\022\071" +
    "\001\002\000\004\017\072\001\002\000\004\022\073\001" +
    "\002\000\004\015\074\001\002\000\004\016\uffde\001\002" +
    "\000\006\007\uffe5\010\uffe5\001\002\000\004\016\111\001" +
    "\002\000\010\002\ufff8\003\ufff8\004\ufff8\001\002\000\004" +
    "\012\105\001\002\000\010\005\006\006\005\011\021\001" +
    "\002\000\004\013\103\001\002\000\004\016\104\001\002" +
    "\000\010\002\ufffa\003\ufffa\004\ufffa\001\002\000\010\005" +
    "\006\006\005\011\021\001\002\000\004\013\107\001\002" +
    "\000\004\016\110\001\002\000\010\002\ufffb\003\ufffb\004" +
    "\ufffb\001\002\000\010\002\ufff9\003\ufff9\004\ufff9\001\002" +
    "\000\004\002\uffff\001\002\000\004\002\ufffd\001\002\000" +
    "\004\002\000\001\002\000\004\016\121\001\002\000\006" +
    "\016\uffec\017\117\001\002\000\004\022\116\001\002\000" +
    "\004\016\uffeb\001\002\000\014\003\ufff2\004\ufff2\005\006" +
    "\006\005\022\ufff2\001\002\000\010\003\ufff1\004\ufff1\022" +
    "\ufff1\001\002\000\004\016\136\001\002\000\004\016\134" +
    "\001\002\000\010\014\126\016\uffec\017\117\001\002\000" +
    "\004\023\127\001\002\000\004\015\130\001\002\000\006" +
    "\016\uffea\017\131\001\002\000\004\022\133\001\002\000" +
    "\004\016\uffe9\001\002\000\004\014\126\001\002\000\014" +
    "\003\uffee\004\uffee\005\006\006\005\022\uffee\001\002\000" +
    "\010\003\uffed\004\uffed\022\uffed\001\002\000\014\003\ufff0" +
    "\004\ufff0\005\006\006\005\022\ufff0\001\002\000\010\003" +
    "\uffef\004\uffef\022\uffef\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\135\000\016\003\006\004\013\005\007\007\010\010" +
    "\012\011\003\001\001\000\002\001\001\000\006\012\122" +
    "\013\123\001\001\000\004\012\114\001\001\000\002\001" +
    "\001\000\006\004\112\005\007\001\001\000\006\004\111" +
    "\005\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\006\022\007\023\010\012\011\003\016\021\023\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\017\060" +
    "\020\036\021\041\022\040\001\001\000\002\001\001\000" +
    "\006\014\024\015\025\001\001\000\012\017\037\020\036" +
    "\021\041\022\040\001\001\000\006\014\034\015\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\017\050\020\036" +
    "\021\041\022\040\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\006\101\007" +
    "\023\010\012\011\003\016\021\023\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\006" +
    "\105\007\023\010\012\011\003\016\021\023\017\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\117\001\001\000\002\001\001\000\010\007\121\010\012" +
    "\011\003\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\131\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\007\134\010\012" +
    "\011\003\001\001\000\002\001\001\000\010\007\136\010" +
    "\012\011\003\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public void report_error (String message, Object info) {
		StringBuffer m = new StringBuffer("Error");

		if (info instanceof java_cup.runtime.Symbol) {
			java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
			if (s.left >= 0) {
				m.append(" en la linea "+(s.left));
				if (s.right >= 0)
					m.append(", columna "+(s.right));
			}
		}
		m.append(" : "+message);
		System.err.println(m);
	}

	public void report_fatal_error(String message, Object info) {
		report_error(message,info);
		System.exit(1);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OP5 ::= operadorQuinario l_paren ident comma ident comma ident comma ident comma ident r_paren 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*OP5*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OP2 ::= operadorBinario l_paren ident comma ident r_paren 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*OP2*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // OP1 ::= operadorUnario l_paren ident r_paren 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*OP1*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // OP ::= OP2 semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*OP*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OP ::= OP1 semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*OP*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPS ::= OP OPS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*OPS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPS ::= OP 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*OPS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPS_GEN ::= OP5 semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(12/*OPS_GEN*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ARC ::= ident equal ident connector ident semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*ARC*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ARCS ::= ARC ARCS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*ARCS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ARCS ::= ARC 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*ARCS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // IDENTS_WEIGHTED ::= ident l_paren number r_paren comma IDENTS_WEIGHTED 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*IDENTS_WEIGHTED*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // IDENTS_WEIGHTED ::= ident l_paren number r_paren 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*IDENTS_WEIGHTED*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // IDENTS ::= ident comma IDENTS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*IDENTS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // IDENTS ::= ident 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*IDENTS*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECL_EDGES ::= edge IDENTS_WEIGHTED semicolon DECL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*DECL_EDGES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECL_EDGES ::= edge IDENTS_WEIGHTED semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*DECL_EDGES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECL_EDGES ::= edge IDENTS semicolon DECL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*DECL_EDGES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECL_EDGES ::= edge IDENTS semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*DECL_EDGES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DECL_NODES ::= node IDENTS semicolon DECL 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*DECL_NODES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // DECL_NODES ::= node IDENTS semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*DECL_NODES*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DECL ::= DECL_EDGES 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*DECL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DECL ::= DECL_NODES 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*DECL*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // BODY ::= OPS_GEN OPS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*BODY*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // BODY ::= DECL ARCS OPS 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*BODY*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // GRAPH ::= error 
            {
              Object RESULT = null;
		 parser.report_error("Error de sintaxis. Es necesario finalizar la definicion del grafo con el caracter punto y coma",null); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // GRAPH ::= error semicolon 
            {
              Object RESULT = null;
		 parser.report_error("Error de sintaxis: No se encuentra el cierre de bloque en la definicion del grafo",null); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // GRAPH ::= error r_bracket semicolon 
            {
              Object RESULT = null;
		 parser.report_error("Error de sintaxis: No se encuentra la apertura de bloque en la definicion del grafo",null); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // GRAPH ::= error l_bracket BODY r_bracket semicolon 
            {
              Object RESULT = null;
		 parser.report_error("Error de sintaxis: No existe identificador de grafo",null); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // GRAPH ::= error ident l_bracket BODY r_bracket semicolon 
            {
              Object RESULT = null;
		 parser.report_error("Error de sintaxis: La definicion del grafo debe iniciarse con la palabra reservada graph",null); 
              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // GRAPH ::= graph ident l_bracket BODY r_bracket semicolon 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*GRAPH*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // GRAPHS_SET ::= GRAPH GRAPHS_SET 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*GRAPHS_SET*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // GRAPHS_SET ::= GRAPH 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*GRAPHS_SET*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // SYNTAX ::= DECL GRAPHS_SET 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*SYNTAX*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= SYNTAX EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // SYNTAX ::= GRAPHS_SET 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*SYNTAX*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

