
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 17 21:58:56 CEST 2009
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int connector = 17;
  public static final int number = 18;
  public static final int graph = 2;
  public static final int r_bracket = 10;
  public static final int operadorQuinario = 8;
  public static final int operadorUnario = 6;
  public static final int edge = 4;
  public static final int l_paren = 11;
  public static final int r_paren = 12;
  public static final int semicolon = 13;
  public static final int op = 5;
  public static final int ident = 16;
  public static final int EOF = 0;
  public static final int equal = 15;
  public static final int node = 3;
  public static final int error = 1;
  public static final int l_bracket = 9;
  public static final int comma = 14;
  public static final int operadorBinario = 7;
}

