pageinfo = [[1243009221,4194],
	[1242638315,9280],
	[1242641413,3566],
	[1242644799,6799],
	[1242621407,2696],
	[1242619425,3720],
	[1243010183,6863],
	[1242620209,6981],
	[1243008439,2674],
	[1243008437,5383],
	[1242640235,2161]];
pagedata = [ ["./instalacion.htm","Instalación","﻿Instalación Top Previous Next La aplicación está implementada en Java y se distribuye empaquetada en un archivo ejecutable con extensión JAR. Por...",""],
["./restricciones.htm","Restricciones","﻿Restricciones Top Previous Next Existe un caso especial en el que el usuario puede tener problemas ya que hay que operar de un modo que no es muy...",""],
["./resultados.htm","Resultados","﻿Resultados Top Previous Next Como se ha comentado a lo largo de este manual, GraphS no sólo es un lenguaje de especificación de grafos si no que ...",""],
["./ejemplos_erroneos.htm","Ejemplos erróneos","﻿Ejemplos erróneos Top Previous Ejemplo 1 En el siguiente ejemplo se observa como un error léxico, producido porque hay identificadores de variabl...",""],
["./compilacion.htm","Compilación","﻿Compilación Top Previous Next Cuando el usuario escribe y abre un fichero GRAPH, puede proceder a la compilación de éste. Para ello, debe pulsa e...",""],
["./introduccion.htm","Introducción","﻿Introducción Top Next La aplicación GraphS permite la especificación de grafos y la realización de operaciones con ellos. Esto se hace a través d...",""],
["./ejemplos_correctos.htm","Ejemplos correctos","﻿Ejemplos correctos Top Previous Next Ejemplo 1 EjemploCorrecto1-GrafoSencillo - Compilación Ejemplo1GrafoSencillo Ejemplo1GrafoSencillo_Floyd Eje...",""],
["./formato_archivos.htm","Formato de archivos","﻿Formato de archivos Top Previous Next Como se podrá observar en los ejemplos que se mostrarán a lo largo de este documento, se ha tratado en la m...",""],
["./salida_de_errores.htm","Salida de errores","﻿Salida de errores Top Previous Next Durante el proceso de compilación se pueden generar dos tipos de mensajes: errores y warnings. Los errores pu...",""],
["./ejecucion_de_la_aplicacion.htm","Ejecucion de la aplicación","﻿Ejecución de la aplicación Top Previous Next En esta sección se procederá a explicar las distintas fases y acciones a realizar para la compilació...",""],
["./ejemplos_de_uso.htm","Ejemplos de uso","﻿Ejemplos de uso Top Previous Next A continuación se mostrarán algunos ejemplos de grafos de tipo GRAPH, es decir, con sintaxis GraphS. En los dos...",""]];
