
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 15 22:33:00 CET 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int connector = 15;
  public static final int number = 17;
  public static final int graph = 2;
  public static final int r_bracket = 9;
  public static final int operadorQuinario = 7;
  public static final int operadorUnario = 5;
  public static final int edge = 4;
  public static final int l_paren = 10;
  public static final int r_paren = 11;
  public static final int semicolon = 12;
  public static final int ident = 16;
  public static final int EOF = 0;
  public static final int equal = 14;
  public static final int node = 3;
  public static final int error = 1;
  public static final int l_bracket = 8;
  public static final int comma = 13;
  public static final int operadorBinario = 6;
}

